"""Adicionado fila data inicial e final + data default

Revision ID: 1dc02d8c59c7
Revises: d398bdcf153a
Create Date: 2025-12-31 12:23:15.130913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc02d8c59c7'
down_revision: Union[str, Sequence[str], None] = 'd398bdcf153a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
