"""Migracao payload

Revision ID: 472f90bc74f7
Revises: 
Create Date: 2025-12-30 12:54:38.886319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472f90bc74f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payloads_data'), 'payloads', ['data'], unique=False)
    op.create_index(op.f('ix_payloads_description'), 'payloads', ['description'], unique=False)
    op.create_index(op.f('ix_payloads_duration_minutes'), 'payloads', ['duration_minutes'], unique=False)
    op.create_index(op.f('ix_payloads_id'), 'payloads', ['id'], unique=False)
    op.create_index(op.f('ix_payloads_target_price'), 'payloads', ['target_price'], unique=False)
    op.create_index(op.f('ix_payloads_url'), 'payloads', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payloads_url'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_target_price'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_id'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_duration_minutes'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_description'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_data'), table_name='payloads')
    op.drop_table('payloads')
    # ### end Alembic commands ###
