"""Alteração de duracao para status

Revision ID: caff1ba939b9
Revises: 472f90bc74f7
Create Date: 2025-12-30 18:46:38.164145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caff1ba939b9'
down_revision: Union[str, Sequence[str], None] = '472f90bc74f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payloads', sa.Column('status', sa.String(), nullable=True))
    op.drop_index(op.f('ix_payloads_duration_minutes'), table_name='payloads')
    op.create_index(op.f('ix_payloads_status'), 'payloads', ['status'], unique=False)
    op.drop_column('payloads', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payloads', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payloads_status'), table_name='payloads')
    op.create_index(op.f('ix_payloads_duration_minutes'), 'payloads', ['duration_minutes'], unique=False)
    op.drop_column('payloads', 'status')
    # ### end Alembic commands ###
