"""Adicionado fila data inicial e final

Revision ID: d398bdcf153a
Revises: fa369a90104a
Create Date: 2025-12-31 12:17:40.492700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd398bdcf153a'
down_revision: Union[str, Sequence[str], None] = 'fa369a90104a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payloads', 'initial_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using="initial_date::date",
               existing_nullable=True),
    op.alter_column('payloads', 'end_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
            postgresql_using="end_date::date",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payloads', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('payloads', 'initial_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
