"""Adicionado fila data inicial e final

Revision ID: fa369a90104a
Revises: caff1ba939b9
Create Date: 2025-12-31 12:16:25.838639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa369a90104a'
down_revision: Union[str, Sequence[str], None] = 'caff1ba939b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payloads', sa.Column('queue', sa.Integer(), nullable=True))
    op.add_column('payloads', sa.Column('initial_date', sa.String(), nullable=True))
    op.add_column('payloads', sa.Column('end_date', sa.String(), nullable=True))
    op.create_index(op.f('ix_payloads_end_date'), 'payloads', ['end_date'], unique=False)
    op.create_index(op.f('ix_payloads_initial_date'), 'payloads', ['initial_date'], unique=False)
    op.create_index(op.f('ix_payloads_queue'), 'payloads', ['queue'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payloads_queue'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_initial_date'), table_name='payloads')
    op.drop_index(op.f('ix_payloads_end_date'), table_name='payloads')
    op.drop_column('payloads', 'end_date')
    op.drop_column('payloads', 'initial_date')
    op.drop_column('payloads', 'queue')
    # ### end Alembic commands ###
